import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900">
        <nav className="bg-white shadow-sm border-b px-4 py-3">
          <div className="max-w-6xl mx-auto flex justify-between items-center">
            <a href="/" className="font-bold text-xl text-blue-600">SBD Shop</a>
            <div className="space-x-4">
              <a href="/items" className="text-gray-600 hover:text-blue-500">Items</a>
              <a href="/profile" className="text-gray-600 hover:text-blue-500">Profil</a>
              <a href="/login" className="text-gray-600 hover:text-blue-500">Login</a>
              <a href="/register" className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Register</a>
            </div>
          </div>
        </nav>
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
